services:
  lesson:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${LESSON_PATH}/app/Dockerfile
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-20s}
      - REMOTE_PEERS=${REMOTE_PEERS:-/ip4/172.16.16.17/tcp/9092}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/stdout.log:/app/stdout.log
    networks:
      workshop-net:
        ipv4_address: 172.16.16.16

  checker:
    image: ghcr.io/libp2p/universal-connectivity-workshop/ucw-checker-03-ping-checkpoint
    container_name: ucw-checker-03-ping-checkpoint
    depends_on:
      - lesson
    stop_grace_period: 1m
    environment:
      - TIMEOUT_DURATION=${TIMEOUT_DURATION:-20s}
      - REMOTE_PEERS=${REMOTE_PEERS:-/ip4/172.16.16.17/tcp/9092}
    volumes:
      - ${PROJECT_ROOT}/${LESSON_PATH}/checker.log:/app/checker.log
    networks:
      workshop-net:
        ipv4_address: 172.16.16.17

networks:
  workshop-net:
    name: workshop-net
    external: true